module Names exposing (namesForTeam, teamToLetter)

namesForTeam : Int -> List String
namesForTeam team =
    listGet team names |> Maybe.withDefault ["____"]

teamToLetter : Int -> String
teamToLetter team =
    case team of
        1 -> "C"
        2 -> "E"
        3 -> "H"
        4 -> "L"
        5 -> "M"
        6 -> "J"
        7 -> "D"
        _ -> "XX"

listGet : Int -> List a -> Maybe a
listGet index list =
    if index < 1 then
        Nothing
    else
        case list of
            head :: tail ->
                if index == 1 then
                    Just head
                else
                    listGet (index - 1) tail

            [] ->
                Nothing


names : List (List String)
names = 
    [[
    "Callie"
    ,"Calvin"
    ,"Carl"
    ,"Carlos"
    ,"Caroline"
    ,"Carson"
    ,"Casey"
    ,"Catherine"
    ,"Chloe"
    ,"Charles"
    ,"Cayden"
    ,"Celia"
    ,"Cerys"
    ,"Ciaran"
    ,"Clark"
    ,"Clayton"
    ,"Coby"
    ,"Codie"
    ,"Colin"
    ,"Connor"
    ,"Corben"
    ,"Cordelia"
    ,"Courtney"
    ,"Craig"
    ,"Cristian"
    ,"Cruz"
    ,"Charlotte"
    ], [
    "Elizabeth"
    ,"Effie"
    ,"Eira"
    ,"Eliot"
    ,"Elle"
    ,"Elodie"
    ,"Eve"
    ,"Evelyn"
    ,"Elsa"
    ,"Elspeth"
    ,"Elvis"
    ,"Emerson"
    ,"Emilia"
    ,"Emmanuel"
    ,"Emmett"
    ,"Erik"
    , "Evan"
    ,"Esmee"
    ,"Esther"
    ,"Ethan"
    ,"Etta"
    ,"Elouise"
    ],[
     "Hadi"
    ,"Halle"
    ,"Hannah"
    ,"Harley"
    ,"Harlow"
    ,"Harman"
    ,"Harriette"
    ,"Harris"
    ,"Hawa"
    ,"Hazel"
    ,"Hector"
    ,"Heidi"
    ,"Hendrix"
    ,"Huxley"
    ,"Henry"
    ,"Herbert"
    ,"Hettie"
    ,"Hugh"
    ,"Honor"
    ,"Huda"
    ,"Huey"
    ,"Hugo"
    ,"Humphrey"
    ,"Hunter"
    ,"Hussain"
    ] ,
    [ "Lachlan"
    ,"Lavinia"
    ,"Layla-Rose"
    ,"Leah"
    ,"Leena"
    ,"Leonardo"
    ,"Lewis"
    ,"Leyla"
    ,"Lia"
    ,"Liana"
    ,"Lillian"
    ,"Lilly"
    ,"Lincoln"
    ,"Logan"
    ,"Lorena"
    ,"Lottie"
    ,"Louis"
    ,"Lowri"
    ,"Lucian"
    ,"Lucy"
    ,"Luka Mabel"
    ], 
    [ "Mark"
    ,"Marta"
    ,"Macey"
    ,"Milo"
    ,"Mackenzie"
    ,"Maddie"
    ,"Mae"
    ,"Maeve"
    ,"Malakai"
    ,"Mali"
    ,"Marcie"
    ,"Marley"
    ,"Maryam"
    ,"Maximillian"
    ,"Mayson"
    ,"Meghan"
    ,"Melanie"
    ,"Melisa"
    ,"Melody"
    ,"Miah"
    ,"Mikael"
    ,"Mila"
    ,"Miles"
    ], [
    "Jacob"
    ,"Jaden"
    ,"Jago"
    ,"Jake"
    ,"James"
    ,"Jan"
    ,"Jasmin"
    ,"Jason"
    ,"Jackson"
    ,"Jayce"
    ,"Jayden"
    ,"Jenna"
    ,"Jensen"
    ,"Jenson"
    ,"Jesse"
    ,"Jett"
    ,"Jimmy"
    ,"Joe"
    ,"Jonathan"
    ,"Jordan"
    ,"Josh"
    ,"Josiah"
    ,"Joy"
    ,"Juan"
    ,"Julian"
    ], [
    "Daisy"
    ,"Dale"
    ,"Damien"
    ,"Damon"
    ,"Dana"
    ,"Dante"
    ,"Darren"
    ,"David"
    ,"Dawson"
    ,"Dean"
    ,"Delilah"
    ,"Demi"
    ,"Dennis"
    ,"Denzel"
    ,"Destiny"
    ,"Devon"
    ,"Dillon"
    ,"Dolly"
    ,"Donnie"
    ,"Dorothy"
    ,"Drew"
    ,"Dua"
    ,"Dulcie"
    ,"Dylan"
    ]]